# Generated by Django 5.0.2 on 2024-02-08 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], max_length=20)),
                ('weight_limit', models.FloatField()),
                ('battery_capacity', models.IntegerField()),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.drone')),
            ],
        ),
        migrations.CreateModel(
            name='DroneMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_timestamp', models.DateTimeField(blank=True, null=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.drone')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.medication')),
            ],
        ),
    ]
